apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: vote
  labels:
    name: postgres-deployment
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-pod
      app: demo-voting-app
  template:
    metadata:
      namespace: vote
      labels:
        name: postgres-pod
        app: demo-voting-app
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
          env:
          - name: POSTGRES_HOST_AUTH_METHOD
            value: "trust"
      volumes:
        - name: db-data
          emptyDir: {}
