apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
  namespace: vote
  labels:
    name: result-app-deployment
    app: demo-voting-app
spec:
  template:
    metadata:
      name: result
      namespace: vote
      labels:
        name: result-app-pod
        app: demo-voting-app
    spec:
      containers:
      - name: result-app
        image: dockersamples/examplevotingapp_result
        ports:
        - containerPort: 80
  selector:
    matchLabels:
      name: result-app-pod
      app: demo-voting-app
    