apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  namespace: vote
  labels:
    name: voting-app-deployment
    app: demo-voting-app
spec:
  template:
    metadata:
      name: vote
      namespace: vote
      labels:
        name: voting-app-pod
        app: demo-voting-app
    spec:
      containers:
      - name: voting-app
        image: dockersamples/examplevotingapp_vote
        ports:
        - containerPort: 80
  selector:
    matchLabels:
      name: voting-app-pod
      app: demo-voting-app
    