apiVersion: v1
kind: Service
metadata:
  name: vote
  namespace: vote
  labels:
    name: voting-service
    app: demo-voting-app
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 80
    nodePort: 31000
  selector:
    name: voting-app-pod
    app: demo-voting-app